markdown: kramdown
highlighter: rouge
permalink: pretty
title: Joonsun Hwang
tagline: Human–AI Collaboration
description: PhD researcher at Carnegie Mellon University.
url: https://hjunsun.github.io
baseurl: ""
author:
  name: Joonsun Hwang
  url: https://hjunsun.github.io
  github: https://github.com/hjunsun
  linkedin: https://www.linkedin.com/in/joon111
plugins:
  - jekyll-feed
exclude:
  - public/Joonsun-Hwang-CV.docx
  - README.md
  - hyde_readme.md
  - Gemfile
  - Gemfile.lock
